version: '3'
networks:
  ehrbase-net:
    driver: bridge

services:
  ehrdb:
    image: ehrbase/ehrbase-v2-postgres:16.2
    networks: [ehrbase-net]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
    ports: ['5432:5432']
    volumes:
      - ehrbase_data:/var/lib/postgresql/data

  ehrbase:
    image: ehrbase/ehrbase:latest
    networks: [ehrbase-net]
    depends_on: [ehrdb]
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: ehrbase-user
      SECURITY_AUTHPASSWORD: SuperSecretPassword
      SERVER_NODENAME: sensire.ehrbase.local
    ports: ['8080:8080']

volumes:
  ehrbase_data:
